version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID}
        - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
        - NEXT_PUBLIC_ENS_DOMAIN=${NEXT_PUBLIC_ENS_DOMAIN}
        - NEXT_PUBLIC_APP_DOMAIN=${NEXT_PUBLIC_APP_DOMAIN}
        - NEXT_PUBLIC_APP_ORIGIN=${NEXT_PUBLIC_APP_ORIGIN}
        - NEXT_PUBLIC_ENS_API_KEY=${NEXT_PUBLIC_ENS_API_KEY}
        - NEXT_PUBLIC_MAINNET_RPC_URL=${NEXT_PUBLIC_MAINNET_RPC_URL}
        - NEXT_PUBLIC_MEMBERS_ONLY=${NEXT_PUBLIC_MEMBERS_ONLY}
    ports:
      - '3000:3000'
    env_file:
      - .env # Load all variables from .env file for runtime
    environment:
      NODE_ENV: production
